// Domain layer (pure Rust, canon-aligned). These compile into the integrity zome
// and are unit-tested on the host. They model structure and validation only —
// never PRU value (value lives in the prose canon, suspended at zero until gates
// clear). See claim.rs for the binary admissibility gate.
//
// NOTE: no `init` extern here. An integrity zome must not define `init` — the
// coordinator zome owns it. Defining `init` in both makes the coordinator (which
// depends on this crate for `EntryTypes`) link two `init` symbols → duplicate
// symbol at wasm link time. The integrity zome's externs are `validate` and the
// entry/link-type defs, generated by the macros below.
pub mod valueflows;
pub mod holo_entries;
pub mod entries;
pub mod ohe;
pub mod mrv;
pub mod claim;
pub mod no_double_counting;
pub mod entry_types;
pub use entry_types::{EntryTypes, UnitEntryTypes};
